services:
  # A Docker web service
  - type: web
    name: chii-webdis
    runtime: docker
    repo: https://github.com/cnt000paramount/chii-docker.git
    region: frankfurt
    branch: main
    rootDir: chii-webdis
    dockerCommand: docker run --name chii-image -p 9000:9000 -d chii-image
    numInstances: 1
    healthCheckPath: /target.js
